//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUpdate.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MUpdate.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MUpdate already checking for updates in background..
        /// </summary>
        internal static string asyncAlreadyRunning {
            get {
                return ResourceManager.GetString("asyncAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at.
        /// </summary>
        internal static string atTag {
            get {
                return ResourceManager.GetString("atTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured while looking for updates..
        /// </summary>
        internal static string checkError {
            get {
                return ResourceManager.GetString("checkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update checking error.
        /// </summary>
        internal static string checkErrorTitle {
            get {
                return ResourceManager.GetString("checkErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current version.
        /// </summary>
        internal static string currentVersion {
            get {
                return ResourceManager.GetString("currentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details:.
        /// </summary>
        internal static string detailsTag {
            get {
                return ResourceManager.GetString("detailsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The update download was cancelled. The application has not been modifed..
        /// </summary>
        internal static string downloadCancelled {
            get {
                return ResourceManager.GetString("downloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update Donwload Cancelled.
        /// </summary>
        internal static string downloadCancelledTitle {
            get {
                return ResourceManager.GetString("downloadCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloaded .
        /// </summary>
        internal static string downloadedTag {
            get {
                return ResourceManager.GetString("downloadedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There was a problem downloading the update. Please try again later..
        /// </summary>
        internal static string downloadError {
            get {
                return ResourceManager.GetString("downloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update Download Error.
        /// </summary>
        internal static string downloadErrorTitle {
            get {
                return ResourceManager.GetString("downloadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Estimated remaining time:.
        /// </summary>
        internal static string estimatedTimeRemainingLbl {
            get {
                return ResourceManager.GetString("estimatedTimeRemainingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latest version already installed..
        /// </summary>
        internal static string latestVersionInstalled {
            get {
                return ResourceManager.GetString("latestVersionInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already have the latest version:.
        /// </summary>
        internal static string latestVersionInstalledLbl {
            get {
                return ResourceManager.GetString("latestVersionInstalledLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It seems you are not connected to Internet. Please retry later..
        /// </summary>
        internal static string noInternetConnectionError {
            get {
                return ResourceManager.GetString("noInternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of.
        /// </summary>
        internal static string ofTag {
            get {
                return ResourceManager.GetString("ofTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Patch Notes:.
        /// </summary>
        internal static string patchNotes {
            get {
                return ResourceManager.GetString("patchNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting download....
        /// </summary>
        internal static string startingDownload3P {
            get {
                return ResourceManager.GetString("startingDownload3P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update available.
        /// </summary>
        internal static string updateAvailable {
            get {
                return ResourceManager.GetString("updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update checking.
        /// </summary>
        internal static string updateChecking {
            get {
                return ResourceManager.GetString("updateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update version.
        /// </summary>
        internal static string updateVersion {
            get {
                return ResourceManager.GetString("updateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verifying download....
        /// </summary>
        internal static string verifyingDownload3P {
            get {
                return ResourceManager.GetString("verifyingDownload3P", resourceCulture);
            }
        }
    }
}
